---
# copyed from https://github.com/Oefenweb/ansible-postfix/blob/master/tasks/main.yml
- name: configure debconf
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ postfix_debconf_selections }}"
  notify: Reconfigure Postfix
  tags:
    - mail
    - postfix
    - debconf
