---
- name: Install base packages
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:      
    - postfix
    - postfix-pcre
    - mailutils
  tags:
    - apt
    - mail
    - packages
    - postfix

- name: Install or remove postfix_srs
  apt:
  apt:
    name: "{{ packages }}"
    state: "{% if postfix_srs %}present{% else %}absent{% endif %}"
  vars:
    packages:      
    - postsrsd
  tags:
    - apt
    - mail
    - packages
    - postsrsd
    - postfix
