---
- name: Install base packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - postfix
    - postfix-pcre
    - mailutils
  tags:
    - apt
    - mail
    - packages
    - postfix

- name: Install or remove postfix_srs
  apt:
    pkg: "{{ item }}"
    state: "{% if postfix_srs %}present{% else %}absent{% endif %}"
  with_items:
    - postsrsd
  tags:
    - apt
    - mail
    - packages
    - postsrsd
    - postfix
