---
- name: Ufw switch smtp
  ufw:
    name: Postfix
    rule: allow
    delete: "{% if postfix_smtp_public %}no{% else %}yes{% endif %}"
  tags:
    - mail
    - ufw

- name: Ufw switch submission
  ufw:
    name: Postfix Submission
    rule: allow
    delete: "{% if postfix_submission_public %}no{% else %}yes{% endif %}"
  tags:
    - mail
    - ufw
